import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.min.css';
import Services from "@/components/services";
import Reviews from "@/components/reviews";
import ContactUs from "@/components/contactus";
import DropMenu from "@/components/dropMenu";
import Commercial from "@/pages/commercial";
import Residential from "@/pages/residential";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body>
        {children}
        <Services />
        <Reviews />
        <ContactUs />
        <DropMenu />
        <Commercial />
        <Residential />
      </body>
    </html>
  );
}
